<?php

namespace CannyDain\ShortyModules\SimpleShop\Controllers;

use CannyDain\Lib\Routing\Models\Route;
use CannyDain\Shorty\Controllers\ShortyModuleController;
use CannyDain\ShortyModules\SimpleShop\SimpleShopModule;
use CannyDain\ShortyModules\SimpleShop\Views\ProductListView;
use CannyDain\ShortyModules\SimpleShop\Views\SingleProductView;

class SimpleShopController extends ShortyModuleController
{
    public function Index()
    {
        $view = new ProductListView();
        $view->setViewProductRouteTemplate(new Route(__CLASS__, 'ViewProduct', array('#id#')));
        $view->setTitle('All Products');
        $view->setProducts($this->_getModule()->getDatasource()->getAllProducts());

        return $view;
    }

    public function ViewProduct($id)
    {
        $view = new SingleProductView();
        $view->setAddToBasketRoute(new Route(__CLASS__, 'ViewProduct', array($id)));
        $view->setProduct($this->_getModule()->getDatasource()->loadProduct($id));

        return $view;
    }

    protected function _getModuleClassname()
    {
        return SimpleShopModule::SIMPLE_SHOP_MODULE_NAME;
    }

    /**
     * @return SimpleShopModule
     */
    protected function _getModule()
    {
        return parent::_getModule(); // TODO: Change the autogenerated stub
    }
}
