<?php

namespace CannyDain\Lib\UI\Response\TemplatedDocuments\Models\Elements\HTML;

use CannyDain\Lib\UI\Views\ViewInterface;

class BodyElement extends BaseHTMLContainerElement
{
    /**
     * @var ViewInterface
     */
    protected $_view;

    public function __construct()
    {
        parent::__construct('', array());
    }

    public function display(ViewInterface $view)
    {
        $this->_view = $view;
        $this->_classes[] = strtr(get_class($this->_view), array('\\' => '-'));

        parent::display($view); // TODO: Change the autogenerated stub
    }


    /**
     * @return string
     */
    protected function _getTagName()
    {
        return 'body';
    }
}