<?php

namespace CannyDain\Shorty\UI\Response;

use CannyDain\Lib\UI\Response\TemplatedDocuments\TemplatedDocument;
use CannyDain\Lib\UI\Views\ViewInterface;

class ShortyTemplatedHTMLDocument extends TemplatedDocument
{
    public function display(ViewInterface $view = null)
    {
        echo '<!DOCTYPE html>';
        parent::display($view); // TODO: Change the autogenerated stub
    }

}