<?php

namespace CannyDain\ShortyModules\Invoice\Manager;

use CannyDain\Shorty\Consumers\ModuleConsumer;
use CannyDain\Shorty\Finance\Interfaces\InvoiceItemInterface;
use CannyDain\Shorty\Finance\Interfaces\InvoiceInterface;
use CannyDain\Shorty\Modules\ModuleManager;
use CannyDain\ShortyModules\Invoice\InvoiceModule;
use CannyDain\ShortyModules\Invoice\Models\Invoice;
use CannyDain\ShortyModules\Invoice\Models\InvoiceItem;

class InvoiceManager extends \CannyDain\Shorty\Finance\InvoiceManager implements ModuleConsumer
{
    /**
     * @var InvoiceModule
     */
    protected $_invoiceModule;

    public function updateItemDiscounts($invoiceID)
    {
        parent::updateItemDiscounts($invoiceID); // TODO: Change the autogenerated stub
    }

    public function getInvoiceByID($id)
    {
        return $this->_invoiceModule->getDatasource()->getInvoiceByID($id);
    }

    public function saveInvoice(InvoiceInterface $invoice)
    {
        if ($invoice instanceof Invoice)
            $invoice->save();
    }

    public function saveInvoiceItem(InvoiceItemInterface $invoiceItem)
    {
        if ($invoiceItem instanceof InvoiceItem)
            $invoiceItem->save();
    }

    public function createInvoice()
    {
        return $this->_invoiceModule->getDatasource()->createInvoice();
    }

    public function createInvoiceItem()
    {
        return $this->_invoiceModule->getDatasource()->createInvoiceItem();
    }

    public function getItemsByInvoice($invoiceID)
    {
        return $this->_invoiceModule->getDatasource()->getInvoiceItemsByInvoiceID($invoiceID);
    }

    public function consumeModuleManager(ModuleManager $manager)
    {
        $this->_invoiceModule = $manager->getModuleByClassname(InvoiceModule::INVOICE_MODULE_NAME);
    }
}